# Copyright (C) 2024 MediaTek Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See http://www.gnu.org/licenses/gpl-2.0.html for more details.
#
#
ccflags-y += -I$(src)              	# needed for trace events
ccflags-y += -I$(srctree)/mm
ccflags-y += -I$(DEVICE_MODULES_PATH)/include/linux
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk_zram
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk_zram/hw

# SPDX-License-Identifier: GPL-2.0-only
