# SPDX-License-Identifier: GPL-2.0
# obj-$(CONFIG_UFCS_CLASS)		+= ufcs_class.o
obj-$(CONFIG_WIRELESS_SC96231)		+= sc96231.o
sc96231-objs := sc96231_tx.o sc96231_mtp_program.o
obj-$(CONFIG_WIRELESS_SC96281)		+= sc96281.o
sc96281-objs := sc96281_charger.o sc96281_mtp_program.o
obj-$(CONFIG_WIRELESS_CHG_CLASS_INTF)		+= wireless_charger_class.o
obj-$(CONFIG_XM_WLS_MANAGER)		+= wls_cp_manager.o
