obj-$(CONFIG_SOUTHCHIP_ADAPTER_CLASS)	+= adapter_class.o

obj-$(CONFIG_SOUTHCHIP_CHARGER_CLASS)	+= charger_class.o

obj-$(CONFIG_SOUTHCHIP_DVCHG_CLASS)		+= dvchg_class.o

obj-$(CONFIG_SOUTHCHIP_LED_CLASS)		+= led_class.o

