obj-$(CONFIG_DEVICE_MODULES_LEDS_MT6370_FLASH)	+= leds-mt6370-flash.o
obj-$(CONFIG_LEDS_MT6379)	+= leds-mt6379.o
obj-$(CONFIG_LEDS_MT6379_PMIC)       += leds-mt6379pmic.o
obj-$(CONFIG_DUAL_LEDS_MT6379_PMIC)       += dual-leds-mt6379pmic.o