# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the phy drivers.
#

ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/ufs
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/ufs/vendor
ccflags-y += -I$(srctree)/drivers/ufs

obj-$(CONFIG_DEVICE_MODULES_PHY_MTK_UFS)              += phy-mtk-ufs.o
