# SPDX-License-Identifier: GPL-2.0
#
# Makefile for sensor chip drivers.
#

#xiaomi thermal control interface
ccflags-y += -DMTK_MI_THERMAL
obj-$(CONFIG_MI_THERMAL_INTERFACE)	+= mi_thermal_interface.o