# SPDX-License-Identifier: GPL-2.0-only

subdir-ccflags-y += -Werror
subdir-ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/                \
                    -I$(DEVICE_MODULES_PATH)/gpu/drm/mediatek/mediatek_v2/     \
                    -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/scp/include/   \
					-I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/

#disp-sync-y := \
#	mtk_drm_virtio_disp.o

#obj-$(CONFIG_MTK_VIRTIO_DISP) += mtk_drm_virtio_disp.o
