obj-$(CONFIG_SIH_VIBRATOR) += si_haptic.o
si_haptic-objs             := haptic.o sih688x_func_config.o haptic_mid.o sih688x.o sih688x_reg.o haptic_misc.o haptic_regmap.o \
								sih6889_func_config.o sih6889.o sih6889_reg.o ringbuffer.o