# common KOs
obj-$(CONFIG_MTK_LPM_LEGACY) += v1/

# platform dependent  KOs

ifneq ($(CONFIG_MTK_LPM_MT6893),)
obj-y += k6893/
endif

ifneq ($(CONFIG_MTK_LPM_MT6877),)
obj-y += k6877/
endif

ifneq ($(CONFIG_MTK_LPM_MT6833),)
obj-y += k6833/
endif

ifneq ($(CONFIG_MTK_LPM_MT6853),)
obj-y += k6853/
endif

ifneq ($(CONFIG_MTK_LPM_MT6789),)
obj-y += k6789/
endif

ifneq ($(CONFIG_MTK_LPM_MT6855),)
obj-y += k6855/
endif
