ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/

obj-m += icnl9916_spi.o
icnl9916_spi-y += cts_driver.o \
                  cts_core.o \
                  cts_sfctrlv2.o \
                  cts_spi_flash.o \
                  cts_firmware.o \
                  cts_test.o \
                  cts_charger_detect.o \
                  cts_earjack_detect.o \
                  cts_tcs.o \
                  cts_platform.o \
                  cts_tool.o \
                  cts_sysfs.o \
                  cts_strerror.o \
                  cts_oem.o