# MIUI ADD: Power_UnionPowerCore
obj-$(CONFIG_MI_UNION_POWER) += unionpower.o
unionpower-$(CONFIG_MI_UNION_POWER) += unionpower_main.o
unionpower-$(CONFIG_MI_UNION_POWER) += frame_load_monitor.o
unionpower-$(CONFIG_MI_UNION_POWER) += union_power_ioctl.o
# END Power_UnionPowerCore
