# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MI_LAUNCH_BOOST)     += lb.o

lb-y += launch_boost_com.o
lb-y += launch_boost.o
lb-y += launch_boost_collect.o
lb-y += launch_boost_preread.o
lb-y += launch_boost_clear.o
lb-y += launch_boost_flush.o
lb-y += launch_boost_dbg.o