# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SOUTHCHIP_CHARGER_MANAGER)	  	+= charger_policy/
obj-$(CONFIG_SOUTHCHIP_CHARGER_CLASS)		+= charger_class/
obj-y		+= common/
obj-$(CONFIG_SC_CHARGER)			+= sc_charger/
