/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __SENINF_TEE_COMMON_H__
#define __SENINF_TEE_COMMON_H__

#include "seninf_reg.h"

#define SENINF_TEE_REG_ADDR_BASE  0x1A004000
#define SENINF_TEE_REG_MAP_REGION 0xA000
#define SENINF_MUX_MAX_NUM 8

typedef enum {
	SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_0	= 0x0010,
	SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_1	= 0x0014,
	SENINF_TEE_REG_ADDR_SENINF_CAM_MUX_CTRL_0	= 0x0400,
	SENINF_TEE_REG_ADDR_SENINF_CAM_MUX_CTRL_1	= 0x0404,
	SENINF_TEE_REG_ADDR_SENINF_CAM_MUX_CTRL_2	= 0x0408,
	SENINF_TEE_REG_ADDR_SENINF_CAM_MUX_CTRL_3	= 0x040c,
	SENINF_TEE_REG_ADDR_SENINF_CAM_MUX_EN		= 0x0410,
	SENINF_TEE_REG_ADDR_SENINF1_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF1_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF1_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF2_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF2_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF2_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF3_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF3_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF3_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF4_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF4_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF4_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF5_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF5_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF5_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF6_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF6_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF6_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF7_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF7_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF7_MUX_OPT		= 0x0D08,
	SENINF_TEE_REG_ADDR_SENINF8_MUX_CTRL_0		= 0x0D00,
	SENINF_TEE_REG_ADDR_SENINF8_MUX_CTRL_1		= 0x0D04,
	SENINF_TEE_REG_ADDR_SENINF8_MUX_OPT		= 0x0D08,
} SENINF_TEE_REG_ADDR;

typedef struct {
	REG_SENINF_MUX_CTRL_0	SENINF_MUX_CTRL_0;
	REG_SENINF_MUX_CTRL_1	SENINF_MUX_CTRL_1;
	REG_SENINF_MUX_OPT	SENINF_MUX_OPT;
} SENINF_TEE_REG_MUX;

typedef struct {
	REG_SENINF_TOP_MUX_CTRL_0	SENINF_TOP_MUX_CTRL_0;
	REG_SENINF_TOP_MUX_CTRL_1	SENINF_TOP_MUX_CTRL_1;
	REG_SENINF_CAM_MUX_CTRL_0	SENINF_CAM_MUX_CTRL_0;
	REG_SENINF_CAM_MUX_CTRL_1	SENINF_CAM_MUX_CTRL_1;
	REG_SENINF_CAM_MUX_CTRL_2	SENINF_CAM_MUX_CTRL_2;
	REG_SENINF_CAM_MUX_CTRL_3	SENINF_CAM_MUX_CTRL_3;
	REG_SENINF_CAM_MUX_EN		SENINF_CAM_MUX_EN;
	SENINF_TEE_REG_MUX		seninf_mux[SENINF_MUX_MAX_NUM];
} SENINF_TEE_REG;

#define SENINF_TEE_REG_GET_ADDR(reg) (SENINF_TEE_REG_ADDR_##reg + SENINF_TEE_REG_ADDR_BASE)

#endif

