# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mi memory info
#
obj-$(CONFIG_MI_MEMORY_SYSFS) += mi_memory.o
mi_memory-$(CONFIG_MI_MEMORY_SYSFS) += mi_memory_mcb.o
mi_memory-$(CONFIG_MI_MEMORY_SYSFS) += ffu-mi.o
mi_memory-$(CONFIG_MI_MEMORY_SYSFS) += mmc_sysfs.o
mi_memory-$(CONFIG_MI_MEMORY_SYSFS) += mmc_hr_ops.o
mi_memory-$(CONFIG_MI_MEMORY_SYSFS) += mv.o



