# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_AW_HAPTIC)  += aw_haptic/
obj-$(CONFIG_SIH_VIBRATOR)  += si_haptic/