ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sda/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/aee/aed/
ccflags-y += -I$(srctree)/kernel/

obj-$(CONFIG_MTK_GIC_RAM_PARITY_CHECK) += gic-ram-parity.o
obj-$(CONFIG_MTK_IRQ_DBG) += irq-dbg.o
obj-$(CONFIG_MTK_LAST_BUS) += last_bus.o
obj-$(CONFIG_MTK_BTM_SUPPORT) += btm/
