// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#include <linux/io.h>

#include <mt6881_dcm_internal.h>
#include <mt6881_dcm_autogen.h>
#include <mtk_dcm.h>
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_l3c_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_L3_SHARE_DCM_CTRL) &
		MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_l3c_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_L3_SHARE_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_L3_SHARE_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_L3_SHARE_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_L3_SHARE_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK ((0x10001U << 0))
#define MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_ON ((0x10001U << 0))
#define MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_acp_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP_ADB_DCM_CFG0) &
		MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_acp_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_MP_ADB_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP_ADB_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_MP_ADB_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP_ADB_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ACP_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK ((0x1fff07ffU << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON ((0x1fff07ffU << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_adb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_ADB_FIFO_DCM_EN) &
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_adb_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_ADB_FIFO_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_ADB_FIFO_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_ADB_FIFO_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_ADB_FIFO_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_MASK ((0xffffffU << 8))
#define MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_ON ((0xfU << 8))
#define MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core0_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1) &
		MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core0_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG1_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE0_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_MASK ((0x1U << 1))
#define MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_MASK ((0xffffffU << 8))
#define MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_ON ((0x1U << 1))
#define MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_ON ((0xfU << 8))
#define MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core1_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1) &
		MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core1_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG1_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE1_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_MASK ((0x1U << 2))
#define MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_MASK ((0xffffffU << 8))
#define MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_ON ((0x1U << 2))
#define MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_ON ((0xfU << 8))
#define MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core2_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1) &
		MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core2_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG1_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE2_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_MASK ((0x1U << 3))
#define MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_MASK ((0xffffffU << 8))
#define MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_ON ((0x1U << 3))
#define MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_ON ((0xfU << 8))
#define MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core3_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1) &
		MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core3_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1,
			(reg_read(MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1) &
			~MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG1_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE3_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_MASK ((0x1U << 4))
#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG1_MASK ((0xffffffU << 2))
#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG2_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_ON ((0x1U << 4))
#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG1_ON ((0xa0c8fU << 3))
#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core4_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_ON);
	ret &= ((reg_read(CHABERTON_CORE4_CONFIG_REG_STALL_DCM_CONF) &
		MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core4_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(CHABERTON_CORE4_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE4_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_ON);
	} else {
		reg_write(CHABERTON_CORE4_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE4_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG2_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE4_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_MASK ((0x1U << 5))
#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG1_MASK ((0xffffffU << 2))
#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG2_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_ON ((0x1U << 5))
#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG1_ON ((0xa0c8fU << 3))
#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core5_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_ON);
	ret &= ((reg_read(CHABERTON_CORE5_CONFIG_REG_STALL_DCM_CONF) &
		MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core5_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(CHABERTON_CORE5_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE5_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_ON);
	} else {
		reg_write(CHABERTON_CORE5_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE5_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG2_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE5_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_MASK ((0x1U << 6))
#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG1_MASK ((0xffffffU << 2))
#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG2_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_ON ((0x1U << 6))
#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG1_ON ((0xa0c8fU << 3))
#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core6_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_ON);
	ret &= ((reg_read(CHABERTON_CORE6_CONFIG_REG_STALL_DCM_CONF) &
		MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core6_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(CHABERTON_CORE6_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE6_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_ON);
	} else {
		reg_write(CHABERTON_CORE6_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE6_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG2_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE6_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_MASK ((0x1U << 7))
#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG1_MASK ((0xffffffU << 2))
#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG2_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_ON ((0x1U << 7))
#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG1_ON ((0xa0c8fU << 3))
#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_core7_stall_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_ON);
	ret &= ((reg_read(CHABERTON_CORE7_CONFIG_REG_STALL_DCM_CONF) &
		MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_core7_stall_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(CHABERTON_CORE7_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE7_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_ON);
	} else {
		reg_write(CHABERTON_CORE7_CONFIG_REG_STALL_DCM_CONF,
			(reg_read(CHABERTON_CORE7_CONFIG_REG_STALL_DCM_CONF) &
			~MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG2_OFF);
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CORE7_STALL_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK ((0x1ffffU << 8))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON ((0x1ffffU << 8))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_apb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_apb_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_MP0_DCM_CFG0,
			(reg_read(MCUSYS_PAR_WRAP_MP0_DCM_CFG0) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK ((0x1001U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_ON ((0x1001U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_io_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_L3GIC_ARCH_CG_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_io_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_L3GIC_ARCH_CG_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_L3GIC_ARCH_CG_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_L3GIC_ARCH_CG_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_L3GIC_ARCH_CG_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_IO_DCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK ((0x111U << 16))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_ON ((0x111U << 16))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_ON ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_bus_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG1) &
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_bus_qdcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG1,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG1) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG1,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG1) &
			~MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_BUS_QDCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK ((0x11111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON ((0x11111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_core_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG2) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG3) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_core_qdcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG2,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG2) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG3,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG3) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG2,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG2) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_QDCM_CONFIG3,
			(reg_read(MCUSYS_PAR_WRAP_QDCM_CONFIG3) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_bkr_ldcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_CI700_DCM_CTRL) &
		MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_bkr_ldcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CI700_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_CI700_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CI700_DCM_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_CI700_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BKR_LDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK ((0x7U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_ON ((0x7U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_OFF ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_cbip_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_3TO1_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO1_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_4TO2_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_1TO2_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO5_CONFIG) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_ON);
	ret &= ((reg_read(MCUSYS_PAR_WRAP_CBIP_P2P_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_cbip_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_3TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_3TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_ON);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_ON);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_4TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_4TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_ON);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_1TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_1TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_ON);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO5_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO5_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_ON);
		reg_write(MCUSYS_PAR_WRAP_CBIP_P2P_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_P2P_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_3TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_3TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG0_OFF);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO1_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO1_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG1_OFF);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_4TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_4TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG2_OFF);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_1TO2_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_1TO2_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG3_OFF);
		reg_write(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO5_CONFIG,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_CABGEN_2TO5_CONFIG) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG4_OFF);
		reg_write(MCUSYS_PAR_WRAP_CBIP_P2P_CONFIG0,
			(reg_read(MCUSYS_PAR_WRAP_CBIP_P2P_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_MASK) |
			MCUSYS_PAR_WRAP_MCU_CBIP_DCM_REG5_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_misc_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG) &
		MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_misc_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG,
			(reg_read(MCUSYS_PAR_WRAP_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG) &
			~MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG,
			(reg_read(MCUSYS_PAR_WRAP_MP_CENTRAL_FABRIC_SUB_CHANNEL_CG) &
			~MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_MISC_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_MASK ((0x1U << 2))
#define MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_ON ((0x1U << 2))
#define MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_bkr_div_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_CMN_DIV_CLK_CTRL) &
		MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_bkr_div_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_CMN_DIV_CLK_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_CMN_DIV_CLK_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_CMN_DIV_CLK_CTRL,
			(reg_read(MCUSYS_PAR_WRAP_CMN_DIV_CLK_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_BKR_DIV_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_dsu_acp_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN) &
		MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_dsu_acp_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_ACP_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK ((0xfU << 1))
#define MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_OFF ((0xfU << 1))

bool dcm_mcusys_par_wrap_mcu_chi_mon_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN) &
		MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_chi_mon_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN,
			(reg_read(MCUSYS_PAR_WRAP_ACP_SLAVE_DCM_EN) &
			~MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CHI_MON_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_gic_spi_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_GIC_SPI_SLOW_CK_CFG) &
		MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_gic_spi_dcm(int on)
{
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_GIC_SPI_SLOW_CK_CFG,
			(reg_read(MCUSYS_PAR_WRAP_GIC_SPI_SLOW_CK_CFG) &
			~MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_GIC_SPI_SLOW_CK_CFG,
			(reg_read(MCUSYS_PAR_WRAP_GIC_SPI_SLOW_CK_CFG) &
			~MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK ((0x1U << 2))
#define MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_OFF ((0x1U << 2))

bool dcm_mcusys_par_wrap_mcu_ebg_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(MCUSYS_PAR_WRAP_EBG_CKE_WRAP_FIFO_CFG) &
		MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_ebg_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(MCUSYS_PAR_WRAP_EBG_CKE_WRAP_FIFO_CFG,
			(reg_read(MCUSYS_PAR_WRAP_EBG_CKE_WRAP_FIFO_CFG) &
			~MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_ON);
	} else {
		reg_write(MCUSYS_PAR_WRAP_EBG_CKE_WRAP_FIFO_CFG,
			(reg_read(MCUSYS_PAR_WRAP_EBG_CKE_WRAP_FIFO_CFG) &
			~MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_EBG_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_cpc_pbi_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CPC_CONFIG_REG_CPC_DCM_ENABLE) &
		MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_cpc_pbi_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(CPC_CONFIG_REG_CPC_DCM_ENABLE,
			(reg_read(CPC_CONFIG_REG_CPC_DCM_ENABLE) &
			~MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_ON);
	} else {
		reg_write(CPC_CONFIG_REG_CPC_DCM_ENABLE,
			(reg_read(CPC_CONFIG_REG_CPC_DCM_ENABLE) &
			~MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CPC_PBI_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_MASK ((0x1U << 1))
#define MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_ON ((0x1U << 1))
#define MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_cpc_turbo_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CPC_CONFIG_REG_CPC_DCM_ENABLE) &
		MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_cpc_turbo_dcm(int on)
{
	/* Notice: SECURE_W */
	if (on) {
		reg_write(CPC_CONFIG_REG_CPC_DCM_ENABLE,
			(reg_read(CPC_CONFIG_REG_CPC_DCM_ENABLE) &
			~MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_ON);
	} else {
		reg_write(CPC_CONFIG_REG_CPC_DCM_ENABLE,
			(reg_read(CPC_CONFIG_REG_CPC_DCM_ENABLE) &
			~MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_CPC_TURBO_DCM_REG0_OFF);
	}
}

#define INFRACFG_AO_INFRA_BUS_DCM_REG0_MASK ((0x9U << 0))
#define INFRACFG_AO_INFRA_BUS_DCM_REG1_MASK ((0x1U << 0))
#define INFRACFG_AO_INFRA_BUS_DCM_REG0_ON ((0x1U << 0))
#define INFRACFG_AO_INFRA_BUS_DCM_REG1_ON ((0x1U << 0))
#define INFRACFG_AO_INFRA_BUS_DCM_REG0_OFF ((0x1U << 0))
#define INFRACFG_AO_INFRA_BUS_DCM_REG1_OFF ((0x1U << 0))

bool dcm_infracfg_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(INFRA_BUS_DCM_CTRL) &
		INFRACFG_AO_INFRA_BUS_DCM_REG0_MASK) ==
		INFRACFG_AO_INFRA_BUS_DCM_REG0_ON);
	ret &= ((reg_read(PERI_BUS_DCM_CTRL) &
		INFRACFG_AO_INFRA_BUS_DCM_REG1_MASK) ==
		INFRACFG_AO_INFRA_BUS_DCM_REG1_ON);

	return ret;
}

void dcm_infracfg_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(INFRA_BUS_DCM_CTRL,
			(reg_read(INFRA_BUS_DCM_CTRL) &
			~INFRACFG_AO_INFRA_BUS_DCM_REG0_MASK) |
			INFRACFG_AO_INFRA_BUS_DCM_REG0_ON);
		reg_write(PERI_BUS_DCM_CTRL,
			(reg_read(PERI_BUS_DCM_CTRL) &
			~INFRACFG_AO_INFRA_BUS_DCM_REG1_MASK) |
			INFRACFG_AO_INFRA_BUS_DCM_REG1_ON);
	} else {
		reg_write(INFRA_BUS_DCM_CTRL,
			(reg_read(INFRA_BUS_DCM_CTRL) &
			~INFRACFG_AO_INFRA_BUS_DCM_REG0_MASK) |
			INFRACFG_AO_INFRA_BUS_DCM_REG0_OFF);
		reg_write(PERI_BUS_DCM_CTRL,
			(reg_read(PERI_BUS_DCM_CTRL) &
			~INFRACFG_AO_INFRA_BUS_DCM_REG1_MASK) |
			INFRACFG_AO_INFRA_BUS_DCM_REG1_OFF);
	}
}

#define INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_MASK ((0xfU << 0))
#define INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_ON ((0x0U << 0))
#define INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_OFF ((0xfU << 0))

bool dcm_infracfg_ao_infra_rx_p2p_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(P2P_RX_CLK_ON) &
		INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_MASK) ==
		INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_ON);

	return ret;
}

void dcm_infracfg_ao_infra_rx_p2p_dcm(int on)
{
	if (on) {
		reg_write(P2P_RX_CLK_ON,
			(reg_read(P2P_RX_CLK_ON) &
			~INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_MASK) |
			INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_ON);
	} else {
		reg_write(P2P_RX_CLK_ON,
			(reg_read(P2P_RX_CLK_ON) &
			~INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_MASK) |
			INFRACFG_AO_INFRA_RX_P2P_DCM_REG0_OFF);
	}
}

#define INFRACFG_AO_AXIMEM_BUS_DCM_REG0_MASK ((0x7fU << 14))
#define INFRACFG_AO_AXIMEM_BUS_DCM_REG0_ON ((0x3U << 18))
#define INFRACFG_AO_AXIMEM_BUS_DCM_REG0_OFF ((0x5U << 18))

bool dcm_infracfg_ao_aximem_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(INFRA_AXIMEM_IDLE_BIT_EN_0) &
		INFRACFG_AO_AXIMEM_BUS_DCM_REG0_MASK) ==
		INFRACFG_AO_AXIMEM_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_infracfg_ao_aximem_bus_dcm(int on)
{
	if (on) {
		reg_write(INFRA_AXIMEM_IDLE_BIT_EN_0,
			(reg_read(INFRA_AXIMEM_IDLE_BIT_EN_0) &
			~INFRACFG_AO_AXIMEM_BUS_DCM_REG0_MASK) |
			INFRACFG_AO_AXIMEM_BUS_DCM_REG0_ON);
	} else {
		reg_write(INFRA_AXIMEM_IDLE_BIT_EN_0,
			(reg_read(INFRA_AXIMEM_IDLE_BIT_EN_0) &
			~INFRACFG_AO_AXIMEM_BUS_DCM_REG0_MASK) |
			INFRACFG_AO_AXIMEM_BUS_DCM_REG0_OFF);
	}
}

#define INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_MASK ((0x49U << 3))
#define INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_MASK ((0x1U << 5))
#define INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_ON ((0x49U << 3))
#define INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_ON ((0x1U << 5))
#define INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))
#define INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_OFF ((0x0U << 0))

bool dcm_infra_ao_bcrm_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_0) &
		INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_MASK) ==
		INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_ON);
	ret &= ((reg_read(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_3) &
		INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_MASK) ==
		INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_ON);

	return ret;
}

void dcm_infra_ao_bcrm_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_0) &
			~INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_MASK) |
			INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_ON);
		reg_write(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_3,
			(reg_read(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_3) &
			~INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_MASK) |
			INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_ON);
	} else {
		reg_write(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_0) &
			~INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_MASK) |
			INFRA_AO_BCRM_INFRA_BUS_DCM_REG0_OFF);
		reg_write(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_3,
			(reg_read(VDNR_DCM_TOP_INFRA_PAR_BUS_u_INFRA_PAR_BUS_CTRL_3) &
			~INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_MASK) |
			INFRA_AO_BCRM_INFRA_BUS_DCM_REG1_OFF);
	}
}

#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK ((0x149U << 4))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK ((0x1U << 21))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK ((0x1U << 18))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON ((0x149U << 4))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON ((0x1U << 21))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON ((0x1U << 18))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF ((0x0U << 0))

bool dcm_peri_ao_bcrm_peri_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);

	return ret;
}

void dcm_peri_ao_bcrm_peri_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
	} else {
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF);
	}
}

#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK ((0x3e013U << 1))
#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON ((0x13U << 1))
#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_OFF ((0x3U << 1))

bool dcm_vlp_ao_bcrm_vlp_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_u_VLP_PAR_BUS_CTRL_0) &
		VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) ==
		VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_vlp_ao_bcrm_vlp_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_VLP_PAR_BUS_u_VLP_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_u_VLP_PAR_BUS_CTRL_0) &
			~VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) |
			VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON);
	} else {
		reg_write(VDNR_DCM_TOP_VLP_PAR_BUS_u_VLP_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_u_VLP_PAR_BUS_CTRL_0) &
			~VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) |
			VLP_AO_BCRM_VLP_BUS_DCM_REG0_OFF);
	}
}

