/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024 MediaTek Inc.
 * Author: Anthony Huang <anthony.huang@mediatek.com>
 */

#ifndef __DRV_CLK_MMDVFS_MT6991_H
#define __DRV_CLK_MMDVFS_MT6991_H

#include <dt-bindings/mmdvfs/mmdvfs-clk-mt6991.h>
#include "mtk-mmdvfs-v5.h"

#define VMMRC_APB_BASE			0x31D00000
#define VDISPRC_APB_BASE		0x31E00000
#define MMRC_APB_BASE			0x31F00000

#define RC_XPU0_MUX_SEL_CLR		0x0110C
#define RC_XPU1_MUX_SEL_CLR		0x111FC
#define RC_XPU2_MUX_SEL_CLR		0x20000
#define RC_XPU3_MUX_SEL_CLR		0x30000
#define RC_XPU9_MUX_SEL_CLR		0x72000
#define RC_XPU10_MUX_SEL_CLR	0x73000
#define RC_XPU12_MUX_SEL_CLR	0x75000

#define RC_XPU0_MUX_SEL			0x10000
#define RC_XPU0_MUX_SEL_PRE		0x100D0

static struct mmdvfs_rc mmdvfs_rc[MMDVFS_V5_PWR_NUM] = {
	[MMDVFS_V5_PWR_VMM] = {MMDVFS_V5_PWR_VMM, VMMRC_APB_BASE, 6, MMDVFS_V5_AP_CAM},
	[MMDVFS_V5_PWR_VDISP] = {MMDVFS_V5_PWR_VDISP, VDISPRC_APB_BASE, 5, MMDVFS_V5_AP_MML},
	[MMDVFS_V5_PWR_VCORE] = {MMDVFS_V5_PWR_VCORE, MMRC_APB_BASE, 7, MMDVFS_V5_AP_VEN},
};

static struct mmdvfs_mux mmdvfs_mux[MMDVFS_V5_MUX_NUM] = {
	[MMDVFS_V5_MUX_CAM] = {MMDVFS_V5_MUX_CAM, MMDVFS_V5_PWR_VMM, 0},
	[MMDVFS_V5_MUX_CAMTM] = {MMDVFS_V5_MUX_CAMTM, MMDVFS_V5_PWR_VMM, 1},
	[MMDVFS_V5_MUX_VDE] = {MMDVFS_V5_MUX_VDE, MMDVFS_V5_PWR_VMM, 9},
	[MMDVFS_V5_MUX_IMG] = {MMDVFS_V5_MUX_IMG, MMDVFS_V5_PWR_VMM, 10},
	[MMDVFS_V5_MUX_IPE] = {MMDVFS_V5_MUX_IPE, MMDVFS_V5_PWR_VMM, 11},

	[MMDVFS_V5_MUX_DIS] = {MMDVFS_V5_MUX_DIS, MMDVFS_V5_PWR_VDISP, 0},
	[MMDVFS_V5_MUX_MDP] = {MMDVFS_V5_MUX_MDP, MMDVFS_V5_PWR_VDISP, 1},

	[MMDVFS_V5_MUX_SMI] = {MMDVFS_V5_MUX_SMI, MMDVFS_V5_PWR_VCORE, 0},
	[MMDVFS_V5_MUX_VEN] = {MMDVFS_V5_MUX_VEN, MMDVFS_V5_PWR_VCORE, 1},
	[MMDVFS_V5_MUX_VEN_MDP] = {MMDVFS_V5_MUX_VEN_MDP, MMDVFS_V5_PWR_VCORE, 2},
};

static struct mmdvfs_user mmdvfs_user[MMDVFS_V5_USER_NUM] = {
	[MMDVFS_V5_USER_CAM] = {MMDVFS_V5_USER_CAM, "user-v5-cam", MMDVFS_V5_MUX_CAM, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_IMG] = {MMDVFS_V5_USER_IMG, "user-v5-img", MMDVFS_V5_MUX_IMG, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_VDEC] = {MMDVFS_V5_USER_VDEC, "user-v5-vdec", MMDVFS_V5_MUX_VDE, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_CPC] = {MMDVFS_V5_USER_CPC, "user-v5-cpc", MMDVFS_V5_MUX_CAM, 12, RC_XPU12_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_V5_USER_DISP] = {MMDVFS_V5_USER_DISP, "user-v5-disp", MMDVFS_V5_MUX_DIS, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_MML] = {MMDVFS_V5_USER_MML, "user-v5-mml", MMDVFS_V5_MUX_MDP, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_DPC] = {MMDVFS_V5_USER_DPC, "user-v5-dpc", MMDVFS_V5_MUX_DIS, 0, RC_XPU12_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_V5_USER_SMI] = {MMDVFS_V5_USER_SMI, "user-v5-smi", MMDVFS_V5_MUX_SMI, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_IMG_SMI] = {MMDVFS_V5_USER_IMG_SMI, "user-v5-img-smi", MMDVFS_V5_MUX_SMI, 1, RC_XPU1_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_VCP_SMI] = {MMDVFS_V5_USER_VCP_SMI, "user-v5-vcp-smi", MMDVFS_V5_MUX_SMI, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_MDP] = {MMDVFS_V5_USER_MDP, "user-v5-mdp", MMDVFS_V5_MUX_VEN_MDP, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_JPEGDEC] = {MMDVFS_V5_USER_JPEGDEC, "user-v5-jpegdec", MMDVFS_V5_MUX_VEN_MDP, 1, RC_XPU1_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_JPEGENC] = {MMDVFS_V5_USER_JPEGENC, "user-v5-jpegenc", MMDVFS_V5_MUX_VEN_MDP, 2, RC_XPU2_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_ADAB] = {MMDVFS_V5_USER_ADAB, "user-v5-adab", MMDVFS_V5_MUX_VEN_MDP, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_VENC] = {MMDVFS_V5_USER_VENC, "user-v5-venc", MMDVFS_V5_MUX_VEN, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_USER_MMPC] = {MMDVFS_V5_USER_MMPC, "user-v5-mmpc", MMDVFS_V5_MUX_SMI, 12, RC_XPU12_MUX_SEL_CLR, MAX_LEVEL},


	[MMDVFS_V5_AP_CAM] = {MMDVFS_V5_AP_CAM, "mmdvfs-v5-ap-cam", MMDVFS_V5_MUX_CAM, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_AP_VDE] = {MMDVFS_V5_AP_VDE, "mmdvfs-v5-ap-vde", MMDVFS_V5_MUX_VDE, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_AP_IMG] = {MMDVFS_V5_AP_IMG, "mmdvfs-v5-ap-img", MMDVFS_V5_MUX_IMG, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_AP_IPE] = {MMDVFS_V5_AP_IPE, "mmdvfs-v5-ap-ipe", MMDVFS_V5_MUX_IPE, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_CAM] = {MMDVFS_V5_VCP_CAM, "mmdvfs-v5-vcp-cam", MMDVFS_V5_MUX_CAM, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_VDE] = {MMDVFS_V5_VCP_VDE, "mmdvfs-v5-vcp-vde", MMDVFS_V5_MUX_VDE, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_IMG] = {MMDVFS_V5_VCP_IMG, "mmdvfs-v5-vcp-img", MMDVFS_V5_MUX_IMG, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_IPE] = {MMDVFS_V5_VCP_IPE, "mmdvfs-v5-vcp-ipe", MMDVFS_V5_MUX_IPE, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_V5_AP_DIS] = {MMDVFS_V5_AP_DIS, "mmdvfs-v5-ap-dis", MMDVFS_V5_MUX_DIS, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_AP_MML] = {MMDVFS_V5_AP_MML, "mmdvfs-v5-ap-mml", MMDVFS_V5_MUX_MDP, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_DIS] = {MMDVFS_V5_VCP_DIS, "mmdvfs-v5-vcp-dis", MMDVFS_V5_MUX_DIS, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_MML] = {MMDVFS_V5_VCP_MML, "mmdvfs-v5-vcp-mml", MMDVFS_V5_MUX_MDP, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_V5_AP_SMI] = {MMDVFS_V5_AP_SMI, "mmdvfs-v5-ap-smi", MMDVFS_V5_MUX_SMI, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_AP_VEN] = {MMDVFS_V5_AP_VEN, "mmdvfs-v5-ap-ven", MMDVFS_V5_MUX_VEN, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_AP_MDP] = {MMDVFS_V5_AP_MDP, "mmdvfs-v5-ap-mdp", MMDVFS_V5_MUX_VEN_MDP, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_SMI] = {MMDVFS_V5_VCP_SMI, "mmdvfs-v5-vcp-smi", MMDVFS_V5_MUX_SMI, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_VEN] = {MMDVFS_V5_VCP_VEN, "mmdvfs-v5-vcp-ven", MMDVFS_V5_MUX_VEN, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_V5_VCP_MDP] = {MMDVFS_V5_VCP_MDP, "mmdvfs-v5-vcp-mdp", MMDVFS_V5_MUX_VEN_MDP, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
};

int mmdvfs_mt6993_dfs_vote_by_xpu(const u8 user_id, const u8 level);

static struct mmdvfs_ops mmdvfs_mt6993_ops = {
	.dfs_vote_by_xpu = mmdvfs_mt6993_dfs_vote_by_xpu,
};

static struct mmdvfs_data mmdvfs_data_mt6993 = {
	.rc = mmdvfs_rc,
	.rc_num = MMDVFS_V5_PWR_NUM,
	.mux = mmdvfs_mux,
	.mux_num = MMDVFS_V5_MUX_NUM,
	.user = mmdvfs_user,
	.user_num = MMDVFS_V5_USER_NUM,
	.ops = &mmdvfs_mt6993_ops,
};

#endif /* __DRV_CLK_MMDVFS_MT6991_H */
