#obj-$(CONFIG_MTK_VIDEO_LM3643)     += lm3643.o
#obj-$(CONFIG_MTK_VIDEO_LM3644)     += lm3644.o
obj-$(CONFIG_MTK_VIDEO_OCP81377)   += ocp81377.o
obj-$(CONFIG_MTK_VIDEO_SGM37864)   += sgm37864.o
MTK_CUSTOM_PATH := $(DEVICE_MODULES_PATH)/drivers/misc/mediatek
subdir-ccflags-y += \
	-I$(MTK_CUSTOM_PATH)/flashlight
