# SPDX-License-Identifier: GPL-2.0

#
# Makefile for misc devices that really don't fit anywhere else.
#
#ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

#imgsensor_isp6s_mon-objs += ../../common/v1_1/camera_hw/regulator/
#imgsensor_isp6s_mon-objs += ../../common/v1_1/camera_hw/gpio/
#imgsensor_isp6s_mon-objs += ../../common/v1_1/camera_hw/mclk/
#imgsensor_isp6s_mon-objs += imgsensor_cfg_table.o

imgsensor_isp6s_mon-objs += \
	../common/v1_1/camera_hw/regulator/regulator.o \
	../common/v1_1/camera_hw/gpio/gpio.o \
	../common/v1_1/camera_hw/mclk/mclk.o \

imgsensor_isp6s_mon-objs += camera_hw/imgsensor_cfg_table.o \
