# SPDX-License-Identifier: GPL-2.0
#
# Xiaomi for misc devices.
#

# MIUI ADD: Camera
obj-$(CONFIG_DEVICE_MODULES_DIO_DMABUF_MAPPER) += dio_dma_mapper/
obj-$(CONFIG_CAM_INTENTAWARE_FSYS) += cam_intentaware_fsys/
#END Camera

# Modem ADD: T1 chip
obj-$(CONFIG_MI_T1_CHIP) += mi_t1_chip/
# Modem T1 chip
