# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mi wifi gpio module
#
ccflags-y += -I$(srctree)/kernel_device_modules-6.6/drivers/misc/mediatek/hwid/
obj-$(CONFIG_MI_WIFI_GPIO) += xiaomi_wifi_gpio.o