# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mi build product name
#
ccflags-y += -I$(srctree)/kernel_device_modules-6.6/drivers/misc/mediatek/hwid/
obj-$(CONFIG_BUILD_PRODUCT_NAME) += build_product_name.o