# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mi boot monitor
#
ccflags-y += -Wno-unused-variable -Wno-unused-function
bootmonitor-objs := boot_monitor.o
obj-$(CONFIG_MI_BOOT_MONITOR)             += bootmonitor.o
