# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MT6338_EFUSE)	+= nvmem-mt6338-efuse.o
nvmem-mt6338-efuse-y		:= mt6338-efuse.o
obj-$(CONFIG_MT6681_EFUSE)	+= nvmem-mt6681-efuse.o
nvmem-mt6681-efuse-y		:= mt6681-efuse.o
