subdir-ccflags-y += -Wformat

BUILD_MBRAIN_BRIDGE_MODUDLE_NAME=mtk_mbraink_bridge
obj-${CONFIG_MTK_MBRAINK} += ${BUILD_MBRAIN_BRIDGE_MODUDLE_NAME}.o
${BUILD_MBRAIN_BRIDGE_MODUDLE_NAME}-objs += mbraink_bridge.o mbraink_bridge_gps.o
