# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

obj-$(CONFIG_MTK_CAM_CAL_ISP3_Z) += src/
obj-$(CONFIG_MTK_CAM_CAL_ISP3_M) += src/
obj-$(CONFIG_MTK_CAM_CAL_ISP4_T) += src/
obj-$(CONFIG_MTK_CAM_CAL_ISP4_C) += src/
obj-$(CONFIG_MTK_CAM_CAL) += src/
obj-$(CONFIG_MTK_CAM_CAL_ISP6S_MON) += src/

$(info imgsensor CONFIG_MTK_CAM_CAL_ISP3_Z = $(CONFIG_MTK_CAM_CAL_ISP3_Z))
$(info imgsensor CONFIG_MTK_CAM_CAL_ISP3_M = $(CONFIG_MTK_CAM_CAL_ISP3_M))
$(info imgsensor CONFIG_MTK_CAM_CAL_ISP4_T = $(CONFIG_MTK_CAM_CAL_ISP4_T))
$(info imgsensor CONFIG_MTK_CAM_CAL_ISP4_C = $(CONFIG_MTK_CAM_CAL_ISP4_C))
$(info imgsensor CONFIG_MTK_CAM_CAL = $(CONFIG_MTK_CAM_CAL))
$(info imgsensor CONFIG_MTK_CAM_CAL_ISP6S_MON = $(CONFIG_MTK_CAM_CAL_ISP6S_MON))