/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/*
 * Copyright (c) 2025 MediaTek Inc.
 *
 */


#ifndef _DT_BINDINGS_GCE_MT6878_H
#define _DT_BINDINGS_GCE_MT6878_H

/* assign timeout 0 also means default */
#define CMDQ_NO_TIMEOUT		0xffffffff
#define CMDQ_TIMEOUT_DEFAULT	1000

/* GCE thread priority */
#define CMDQ_THR_PRIO_LOWEST	0
#define CMDQ_THR_PRIO_1		1
#define CMDQ_THR_PRIO_2		2
#define CMDQ_THR_PRIO_3		3
#define CMDQ_THR_PRIO_4		4
#define CMDQ_THR_PRIO_5		5
#define CMDQ_THR_PRIO_6		6
#define CMDQ_THR_PRIO_HIGHEST	7

/* CPR count in 32bit register */
#define GCE_CPR_COUNT		1312

/* GCE subsys table */
#define SUBSYS_1300XXXX		0
#define SUBSYS_1400XXXX		1
#define SUBSYS_1401XXXX		2
#define SUBSYS_1402XXXX		3
#define SUBSYS_1502XXXX		4
#define SUBSYS_1880XXXX		5
#define SUBSYS_1881XXXX		6
#define SUBSYS_1882XXXX		7
#define SUBSYS_1883XXXX		8
#define SUBSYS_1884XXXX		9
#define SUBSYS_1000XXXX		10
#define SUBSYS_1001XXXX		11
#define SUBSYS_1002XXXX		12
#define SUBSYS_1003XXXX		13
#define SUBSYS_1004XXXX		14
#define SUBSYS_1005XXXX		15
#define SUBSYS_1020XXXX		16
#define SUBSYS_1028XXXX		17
#define SUBSYS_1700XXXX		18
#define SUBSYS_1701XXXX		19
#define SUBSYS_1702XXXX		20
#define SUBSYS_1703XXXX		21
#define SUBSYS_1800XXXX		22
#define SUBSYS_1801XXXX		23
#define SUBSYS_1802XXXX		24
#define SUBSYS_1804XXXX		25
#define SUBSYS_1805XXXX		26
#define SUBSYS_1808XXXX		27
#define SUBSYS_180aXXXX		28
#define SUBSYS_180bXXXX		29
#define SUBSYS_NO_SUPPORT	99

/* GCE General Purpose Register (GPR) support
 * Leave note for scenario usage here
 */
/* GCE: write mask */
#define GCE_GPR_R00		0x00
#define GCE_GPR_R01		0x01
/* MDP: P1: JPEG dest */
#define GCE_GPR_R02		0x02
#define GCE_GPR_R03		0x03
/* MDP: PQ color */
#define GCE_GPR_R04		0x04
/* MDP: 2D sharpness */
#define GCE_GPR_R05		0x05
/* DISP: poll esd */
#define GCE_GPR_R06		0x06
#define GCE_GPR_R07		0x07
/* MDP: P4: 2D sharpness dst */
#define GCE_GPR_R08		0x08
#define GCE_GPR_R09		0x09
/* VCU: poll with timeout for GPR timer */
#define GCE_GPR_R10		0x0A
#define GCE_GPR_R11		0x0B
/* CMDQ: debug */
#define GCE_GPR_R12		0x0C
#define GCE_GPR_R13		0x0D
/* CMDQ: P7: debug */
#define GCE_GPR_R14		0x0E
#define GCE_GPR_R15		0x0F

/* GCE-D hardware events */
#define CMDQ_EVENT_MDPSYS_MDP_RDMA0_SOF 0
#define CMDQ_EVENT_MDPSYS_MDP_RDMA1_SOF 1
#define CMDQ_EVENT_MDPSYS_MDP_HDR0_SOF 2
#define CMDQ_EVENT_MDPSYS_MDP_HDR1_SOF 3
#define CMDQ_EVENT_MDPSYS_MDP_AAL0_SOF 4
#define CMDQ_EVENT_MDPSYS_MDP_AAL1_SOF 5
#define CMDQ_EVENT_MDPSYS_MDP_RSZ0_SOF 6
#define CMDQ_EVENT_MDPSYS_MDP_RSZ1_SOF 7
#define CMDQ_EVENT_MDPSYS_MDP_TDSHP0_SOF 8
#define CMDQ_EVENT_MDPSYS_MDP_TDSHP1_SOF 9
#define CMDQ_EVENT_MDPSYS_MDP_COLOR0_SOF 10
#define CMDQ_EVENT_MDPSYS_MDP_WROT0_SOF 11
#define CMDQ_EVENT_MDPSYS_MDP_RSZ2_SOF 12
#define CMDQ_EVENT_MDPSYS_MDP_RSZ3_SOF 13
#define CMDQ_EVENT_MDPSYS_MDP_WROT2_SOF 14
#define CMDQ_EVENT_MDPSYS_MDP_WROT3_SOF 15
#define CMDQ_EVENT_MDPSYS_IMG_DL_RELAY0_SOF 16
#define CMDQ_EVENT_MDPSYS_IMG_DL_RELAY1_SOF 17
#define CMDQ_EVENT_MDPSYS_MDP_WROT3_FRAME_DONE 18
#define CMDQ_EVENT_MDPSYS_MDP_WROT2_FRAME_DONE 19
#define CMDQ_EVENT_MDPSYS_MDP_WROT1_FRAME_DONE 20
#define CMDQ_EVENT_MDPSYS_MDP_WROT0_FRAME_DONE 21
#define CMDQ_EVENT_MDPSYS_MDP_TDSHP1_FRAME_DONE 22
#define CMDQ_EVENT_MDPSYS_MDP_TDSHP0_FRAME_DONE 23
#define CMDQ_EVENT_MDPSYS_MDP_RSZ3_FRAME_DONE 24
#define CMDQ_EVENT_MDPSYS_MDP_RSZ2_FRAME_DONE 25
#define CMDQ_EVENT_MDPSYS_MDP_RSZ1_FRAME_DONE 26
#define CMDQ_EVENT_MDPSYS_MDP_RSZ0_FRAME_DONE 27
#define CMDQ_EVENT_MDPSYS_MDP_RDMA1_FRAME_DONE 28
#define CMDQ_EVENT_MDPSYS_MDP_RDMA0_FRAME_DONE 29
#define CMDQ_EVENT_MDPSYS_MDP_HDR1_FRAME_DONE 30
#define CMDQ_EVENT_MDPSYS_MDP_HDR0_FRAME_DONE 31
#define CMDQ_EVENT_MDPSYS_MDP_FG1_FRAME_DONE 32
#define CMDQ_EVENT_MDPSYS_MDP_FG0_FRAME_DONE 33
#define CMDQ_EVENT_MDPSYS_MDP_COLOR1_FRAME_DONE 34
#define CMDQ_EVENT_MDPSYS_MDP_COLOR0_FRAME_DONE 35
#define CMDQ_EVENT_MDPSYS_MDP_AAL1_FRAME_DONE 36
#define CMDQ_EVENT_MDPSYS_MDP_AAL0_FRAME_DONE 37
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT0 38
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT1 39
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT2 40
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT3 41
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT4 42
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT5 43
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT6 44
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT7 45
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT8 46
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT9 47
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT10 48
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT11 49
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT12 50
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT13 51
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT14 52
#define CMDQ_EVENT_MDPSYS_STREAM_DONE_ENG_EVENT_BIT15 53
#define CMDQ_EVENT_MDPSYS_MDP_WROT3_SW_RST_DONE_ENG_EVENT 54
#define CMDQ_EVENT_MDPSYS_MDP_WROT2_SW_RST_DONE_ENG_EVENT 55
#define CMDQ_EVENT_MDPSYS_MDP_WROT1_SW_RST_DONE_ENG_EVENT 56
#define CMDQ_EVENT_MDPSYS_MDP_WROT0_SW_RST_DONE_ENG_EVENT 57
#define CMDQ_EVENT_MDPSYS_MDP_RDMA1_SW_RST_DONE_ENG_EVENT 58
#define CMDQ_EVENT_MDPSYS_MDP_RDMA0_SW_RST_DONE_ENG_EVENT 59
#define CMDQ_EVENT_MDPSYS_BUF_UNDERRUN_ENG_EVENT_BIT0 60
#define CMDQ_EVENT_MDPSYS_BUF_UNDERRUN_ENG_EVENT_BIT1 61
#define CMDQ_EVENT_MDPSYS_BUF_UNDERRUN_ENG_EVENT_BIT2 62
#define CMDQ_EVENT_MDPSYS_BUF_UNDERRUN_ENG_EVENT_BIT3 63
#define CMDQ_EVENT_MDPSYS_DT_DONE0 64
#define CMDQ_EVENT_MDPSYS_DT_DONE1 65
#define CMDQ_EVENT_MDPSYS_DT_DONE2_MERGE 66
#define CMDQ_EVENT_MDPSYS_DT_DONE3 67
#define CMDQ_EVENT_MDPSYS_DT_DONE4_MERGE 68
#define CMDQ_EVENT_MDPSYS_DT_DONE5 69
#define CMDQ_EVENT_MDPSYS_DT_DONE6_MERGE 70
#define CMDQ_EVENT_MDPSYS_DT_DONE7 71
#define CMDQ_EVENT_MDPSYS_DT_DONE32_MERGE 72
#define CMDQ_EVENT_MDPSYS_DT_DONE33 73
#define CMDQ_EVENT_MDPSYS_DT_DONE34 74
#define CMDQ_EVENT_MDPSYS_DT_DONE35 75
#define CMDQ_EVENT_MDPSYS_MMINFRA_OFF_START 76
#define CMDQ_EVENT_MDPSYS_MMINFRA_OFF_END 77
#define CMDQ_EVENT_MDPSYS_INFRA_OFF_START 78
#define CMDQ_EVENT_MDPSYS_INFRA_OFF_END 79
#define CMDQ_EVENT_MDPSYS_DT_DONE29 80
#define CMDQ_EVENT_MDPSYS_DT_DONE30_MERGE 81
#define CMDQ_EVENT_MDPSYS_DT_DONE31 82
#define CMDQ_EVENT_MDPSYS_DT_DONE54 83
#define CMDQ_EVENT_MDPSYS_DT_DONE55_MERGE 84
#define CMDQ_EVENT_MDPSYS_DT_DONE56 85
#define CMDQ_EVENT_MDPSYS_DPC_MML1_MTCMOS_OFF_PULSE 86
#define CMDQ_EVENT_MDPSYS_DPC_MML1_MTCMOS_ON_PULSE 87
#define CMDQ_EVENT_MDPSYS_DPC_OVL0_MTCMOS_OFF_PULSE 88
#define CMDQ_EVENT_MDPSYS_DPC_OVL0_MTCMOS_ON_PULSE 89
#define CMDQ_EVENT_MDPSYS_DPC_OVL1_MTCMOS_OFF_PULSE 90
#define CMDQ_EVENT_MDPSYS_DPC_OVL1_MTCMOS_ON_PULSE 91
#define CMDQ_EVENT_MDPSYS_DPC_DISP0_MTCMOS_OFF_PULSE 92
#define CMDQ_EVENT_MDPSYS_DPC_DISP0_MTCMOS_ON_PULSE 93
#define CMDQ_EVENT_MDPSYS_DPC_DISP1_MTCMOS_OFF_PULSE 94
#define CMDQ_EVENT_MDPSYS_DPC_DISP1_MTCMOS_ON_PULSE 95
#define CMDQ_EVENT_DISPSYS_DISP_OVL0_2L_SOF 128
#define CMDQ_EVENT_DISPSYS_DISP_OVL1_2L_SOF 129
#define CMDQ_EVENT_DISPSYS_DISP_OVL2_2L_SOF 130
#define CMDQ_EVENT_DISPSYS_DISP_OVL3_2L_SOF 131
#define CMDQ_EVENT_DISPSYS_DISP_UFBC_WDMA0_SOF 132
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_SOF 133
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_SOF 134
#define CMDQ_EVENT_DISPSYS_DISP_WDMA1_SOF 135
#define CMDQ_EVENT_DISPSYS_DISP_PWM0_SOF 136
#define CMDQ_EVENT_DISPSYS_DISP_PWM1_SOF 137
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT0 138
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT1 139
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT2 140
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT3 141
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT4 142
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT5 143
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT6 144
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT7 145
#define CMDQ_EVENT_DISPSYS_PMSR_MOD_FRAME_DONE_BIT8 146
#define CMDQ_EVENT_DISPSYS_DISP_WDMA1_FRAME_DONE 147
#define CMDQ_EVENT_DISPSYS_DISP_UFBC_WDMA0_FRAME_DONE 148
#define CMDQ_EVENT_DISPSYS_DISP_TDSHP1_FRAME_DONE 149
#define CMDQ_EVENT_DISPSYS_DISP_TDSHP0_FRAME_DONE 150
#define CMDQ_EVENT_DISPSYS_DISP_SPLITTER0_FRAME_DONE 151
#define CMDQ_EVENT_DISPSYS_DISP_RSZ1_FRAME_DONE 152
#define CMDQ_EVENT_DISPSYS_DISP_RSZ0_FRAME_DONE 153
#define CMDQ_EVENT_DISPSYS_DISP_POSTMASK0_FRAME_DONE 154
#define CMDQ_EVENT_DISPSYS_DISP_OVL3_2L_FRAME_DONE 155
#define CMDQ_EVENT_DISPSYS_DISP_OVL2_2L_FRAME_DONE 156
#define CMDQ_EVENT_DISPSYS_DISP_OVL1_2L_FRAME_DONE 157
#define CMDQ_EVENT_DISPSYS_DISP_OVL0_2L_FRAME_DONE 158
#define CMDQ_EVENT_DISPSYS_DISP_GAMMA1_FRAME_DONE 159
#define CMDQ_EVENT_DISPSYS_DISP_GAMMA0_FRAME_DONE 160
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_FRAME_DONE 161
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_FRAME_DONE 162
#define CMDQ_EVENT_DISPSYS_DISP_DSC_WRAP0_CORE1_FRAME_DONE 163
#define CMDQ_EVENT_DISPSYS_DISP_DSC_WRAP0_CORE0_FRAME_DONE 164
#define CMDQ_EVENT_DISPSYS_DISP_DITHER1_FRAME_DONE 165
#define CMDQ_EVENT_DISPSYS_DISP_DITHER0_FRAME_DONE 166
#define CMDQ_EVENT_DISPSYS_DISP_COLOR0_FRAME_DONE 167
#define CMDQ_EVENT_DISPSYS_DISP_CCORR3_FRAME_DONE 168
#define CMDQ_EVENT_DISPSYS_DISP_CCORR2_FRAME_DONE 169
#define CMDQ_EVENT_DISPSYS_DISP_CCORR1_FRAME_DONE 170
#define CMDQ_EVENT_DISPSYS_DISP_CCORR0_FRAME_DONE 171
#define CMDQ_EVENT_DISPSYS_DISP_C3D1_FRAME_DONE 172
#define CMDQ_EVENT_DISPSYS_DISP_C3D0_FRAME_DONE 173
#define CMDQ_EVENT_DISPSYS_DISP_AAL0_FRAME_DONE 174
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT0 175
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT1 176
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT2 177
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT3 178
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT4 179
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT5 180
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT6 181
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT7 182
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT8 183
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT9 184
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT10 185
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT11 186
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT12 187
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT13 188
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT14 189
#define CMDQ_EVENT_DISPSYS_STREAM_DONE_ENG_EVENT_BIT15 190
#define CMDQ_EVENT_DISPSYS_DISP_WDMA1_SW_RST_DONE_ENG_EVENT 191
#define CMDQ_EVENT_DISPSYS_DISP_POSTMASK0_RST_DONE_ENG_EVENT 192
#define CMDQ_EVENT_DISPSYS_DISP_OVL3_2L_RST_DONE_ENG_EVENT 193
#define CMDQ_EVENT_DISPSYS_DISP_OVL2_2L_RST_DONE_ENG_EVENT 194
#define CMDQ_EVENT_DISPSYS_DISP_OVL1_2L_RST_DONE_ENG_EVENT 195
#define CMDQ_EVENT_DISPSYS_DISP_OVL0_2L_RST_DONE_ENG_EVENT 196
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_VM_VFP_STR_ENG_EVENT 197
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_VM_VBP_STR_ENG_EVENT 198
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_VM_VACT_STR_ENG_EVENT 199
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_VM_DONE_ENG_EVENT 200
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_VM_CMD_DONE_ENG_EVENT 201
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_TE_TIMEOUT_ENG_EVENT 202
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_TE_ENG_EVENT 203
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_TARGET_LINE_ENG_EVENT 204
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_START_ENG_EVENT 205
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_SLEEPOUT_DONE_ENG_EVENT 206
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_SLEEPIN_ULPS_ENG_EVENT 207
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_SKEWCAL_DONE_ENG_EVENT 208
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_LTPO_VSYNC_ENG_EVENT 209
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_LPRX_RDDATA_RDY_ENG_EVENT 210
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_INTERNAL_SOF_ENG_EVENT 211
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_INP_UNFINISH_ENG_EVENT 212
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_DONE_ENG_EVENT 213
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_CM_DONE_ENG_EVENT 214
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_BUFFER_UNDERRUN_ENG_EVENT 215
#define CMDQ_EVENT_DISPSYS_DISP_DSI1_BTA_TIMEOUT_ENG_EVENT 216
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_VM_VFP_STR_ENG_EVENT 217
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_VM_VBP_STR_ENG_EVENT 218
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_VM_VACT_STR_ENG_EVENT 219
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_VM_DONE_ENG_EVENT 220
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_VM_CMD_DONE_ENG_EVENT 221
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_TE_TIMEOUT_ENG_EVENT 222
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_TE_ENG_EVENT 223
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_TARGET_LINE_ENG_EVENT 224
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_START_ENG_EVENT 225
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_SLEEPOUT_DONE_ENG_EVENT 226
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_SLEEPIN_ULPS_ENG_EVENT 227
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_SKEWCAL_DONE_ENG_EVENT 228
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_LTPO_VSYNC_ENG_EVENT 229
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_LPRX_RDDATA_RDY_ENG_EVENT 230
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_INTERNAL_SOF_ENG_EVENT 231
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_INP_UNFINISH_ENG_EVENT 232
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_DONE_ENG_EVENT 233
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_CM_DONE_ENG_EVENT 234
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_BUFFER_UNDERRUN_ENG_EVENT 235
#define CMDQ_EVENT_DISPSYS_DISP_DSI0_BTA_TIMEOUT_ENG_EVENT 236
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT0 237
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT1 238
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT2 239
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT3 240
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT4 241
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT5 242
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT6 243
#define CMDQ_EVENT_DISPSYS_BUF_UNDERRUN_ENG_EVENT_BIT7 244

/* GCE-M hardware events */
#define CMDQ_EVENT_VENC_VENC_CMDQ_FRAME_DONE 1
#define CMDQ_EVENT_VENC_VENC_CMDQ_PAUSE_DONE 2
#define CMDQ_EVENT_VENC_JPGENC_CMDQ_DONE 3
#define CMDQ_EVENT_VENC_VENC_CMDQ_MB_DONE 4
#define CMDQ_EVENT_VENC_VENC_CMDQ_128BYTE_CNT_DONE 5
#define CMDQ_EVENT_VENC_VENC_CMDQ_PPS_DONE 8
#define CMDQ_EVENT_VENC_VENC_CMDQ_SPS_DONE 9
#define CMDQ_EVENT_VENC_VENC_CMDQ_VPS_DONE 10
#define CMDQ_EVENT_VDEC_GCE_EVENT_0 32
#define CMDQ_EVENT_VDEC_GCE_EVENT_1 33
#define CMDQ_EVENT_VDEC_GCE_EVENT_2 34
#define CMDQ_EVENT_VDEC_GCE_EVENT_3 35
#define CMDQ_EVENT_VDEC_GCE_EVENT_4 36
#define CMDQ_EVENT_VDEC_GCE_EVENT_5 37
#define CMDQ_EVENT_VDEC_GCE_EVENT_6 38
#define CMDQ_EVENT_VDEC_GCE_EVENT_7 39
#define CMDQ_EVENT_VDEC_GCE_EVENT_8 40
#define CMDQ_EVENT_VDEC_GCE_EVENT_9 41
#define CMDQ_EVENT_VDEC_GCE_EVENT_10 42
#define CMDQ_EVENT_VDEC_GCE_EVENT_11 43
#define CMDQ_EVENT_VDEC_GCE_EVENT_12 44
#define CMDQ_EVENT_VDEC_GCE_EVENT_13 45
#define CMDQ_EVENT_VDEC_GCE_EVENT_14 46
#define CMDQ_EVENT_VDEC_GCE_EVENT_15 47
#define CMDQ_EVENT_CAM_ISP_FRAME_DONE_A 65
#define CMDQ_EVENT_CAM_ISP_FRAME_DONE_B 66
#define CMDQ_EVENT_CAM_ISP_FRAME_DONE_C 67
#define CMDQ_EVENT_CAM_CAMSV0_PASS1_DONE 68
#define CMDQ_EVENT_CAM_CAMSV02_PASS1_DONE 69
#define CMDQ_EVENT_CAM_CAMSV1_PASS1_DONE 70
#define CMDQ_EVENT_CAM_CAMSV2_PASS1_DONE 71
#define CMDQ_EVENT_CAM_CAMSV3_PASS1_DONE 72
#define CMDQ_EVENT_CAM_CAMSV4_PASS1_DONE 73
#define CMDQ_EVENT_CAM_CAMSV42_PASS1_DONE 74
#define CMDQ_EVENT_CAM_MRAW_0_PASS1_DONE 75
#define CMDQ_EVENT_CAM_MRAW_1_PASS1_DONE 76
#define CMDQ_EVENT_CAM_SENINF_CAM0_FIFO_FULL 77
#define CMDQ_EVENT_CAM_SENINF_CAM1_FIFO_FULL 78
#define CMDQ_EVENT_CAM_SENINF_CAM2_FIFO_FULL 79
#define CMDQ_EVENT_CAM_SENINF_CAM3_FIFO_FULL 80
#define CMDQ_EVENT_CAM_SENINF_CAM4_FIFO_FULL 81
#define CMDQ_EVENT_CAM_SENINF_CAM5_FIFO_FULL 82
#define CMDQ_EVENT_CAM_SENINF_CAM6_FIFO_FULL 83
#define CMDQ_EVENT_CAM_SENINF_CAM7_FIFO_FULL 84
#define CMDQ_EVENT_CAM_SENINF_CAM8_FIFO_FULL 85
#define CMDQ_EVENT_CAM_SENINF_CAM9_FIFO_FULL 86
#define CMDQ_EVENT_CAM_SENINF_CAM10_FIFO_FULL 87
#define CMDQ_EVENT_CAM_SENINF_CAM11_FIFO_FULL 88
#define CMDQ_EVENT_CAM_SENINF_CAM12_FIFO_FULL 89
#define CMDQ_EVENT_CAM_TG_OVRUN_A_INT 90
#define CMDQ_EVENT_CAM_DMA_R1_ERROR_A_INT 91
#define CMDQ_EVENT_CAM_TG_OVRUN_B_INT 92
#define CMDQ_EVENT_CAM_DMA_R1_ERROR_B_INT 93
#define CMDQ_EVENT_CAM_TG_OVRUN_C_INT 94
#define CMDQ_EVENT_CAM_DMA_R1_ERROR_C_INT 95
#define CMDQ_EVENT_CAM_TG_OVRUN_INT 96
#define CMDQ_EVENT_CAM_DMA_R1_ERROR_M0_INT 97
#define CMDQ_EVENT_CAM_TG_GRABERR_M0_INT 98
#define CMDQ_EVENT_CAM_TG_GRABERR_M1_INT 99
#define CMDQ_EVENT_CAM_TG_GRABERR_A_INT 100
#define CMDQ_EVENT_CAM_CQ_VR_SNAP_A_INT 101
#define CMDQ_EVENT_CAM_TG_GRABERR_B_INT 102
#define CMDQ_EVENT_CAM_CQ_VR_SNAP_B_INT 103
#define CMDQ_EVENT_CAM_TG_GRABERR_C_INT 104
#define CMDQ_EVENT_CAM_CQ_VR_SNAP_C_INT 105
#define CMDQ_EVENT_CAM_PDA_IRQO_EVENT_DONE_D1 106
#define CMDQ_EVENT_CAM_SENINF_CAM13_FIFO_FULL 107
#define CMDQ_EVENT_CAM_SENINF_CAM14_FIFO_FULL 108
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_0 129
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_1 130
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_2 131
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_3 132
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_4 133
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_5 134
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_6 135
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_7 136
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_8 137
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_9 138
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_10 139
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_11 140
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_12 141
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_13 142
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_14 143
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_15 144
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_16 145
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_17 146
#define CMDQ_EVENT_IMG1_DIP_FRAME_DONE_P2_18 147
#define CMDQ_EVENT_IMG1_DIP_DMA_ERR_EVENT 148
#define CMDQ_EVENT_IMG1_AMD_FRAME_DONE 149
#define CMDQ_EVENT_IMG1_MFB_DONE_LINK_MISC 150
#define CMDQ_EVENT_IMG1_WPE_A_DONE_LINK_MISC 151
#define CMDQ_EVENT_IMG1_MSS_DONE_LINK_MISC 152
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_0 161
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_1 162
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_2 163
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_3 164
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_4 165
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_5 166
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_6 167
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_7 168
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_8 169
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_9 170
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_10 171
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_11 172
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_12 173
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_13 174
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_14 175
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_15 176
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_16 177
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_17 178
#define CMDQ_EVENT_IMG2_DIP_FRAME_DONE_P2_18 179
#define CMDQ_EVENT_IMG2_DIP_DMA_ERR_EVENT 180
#define CMDQ_EVENT_IMG2_AMD_FRAME_DONE 181
#define CMDQ_EVENT_IMG2_MFB_DONE_LINK_MISC 182
#define CMDQ_EVENT_IMG2_WPE_A_DONE_LINK_MISC 183
#define CMDQ_EVENT_IMG2_MSS_DONE_LINK_MISC 184
#define CMDQ_EVENT_IPE_FDVT_DONE 193
#define CMDQ_EVENT_IPE_FE_DONE 194
#define CMDQ_EVENT_IPE_RSC_DONE 195
#define CMDQ_EVENT_IPE_DVS_DONE_ASYNC_SHOT 196
#define CMDQ_EVENT_IPE_DVP_DONE_ASYNC_SHOT 197


/* end of hw event and begin of sw token */
#define CMDQ_MAX_HW_EVENT				512

/* CMDQ sw tokens
 * Following definitions are gce sw token which may use by clients
 * event operation API.
 * Note that token 512 to 639 may set secure
 */

/* begin of GCE-D sw token */
/* MML sw tokens */
#define CMDQ_SYNC_TOKEN_MML_BUFA			661
#define CMDQ_SYNC_TOKEN_MML_BUFB			662
#define CMDQ_SYNC_TOKEN_MML_BUF_NEXT			663
#define CMDQ_SYNC_TOKEN_MML_IR_MML_READY		664
#define CMDQ_SYNC_TOKEN_MML_IR_DISP_READY		665
#define CMDQ_SYNC_TOKEN_MML_MML_STOP			666
#define CMDQ_SYNC_TOKEN_MML_PIPE0			667
#define CMDQ_SYNC_TOKEN_MML_PIPE1			668
#define CMDQ_SYNC_TOKEN_MML_PIPE1_NEXT			669
#define CMDQ_SYNC_TOKEN_MML_APU_START           670

/* Config thread notify trigger thread */
#define CMDQ_SYNC_TOKEN_CONFIG_DIRTY			640
/* Trigger thread notify config thread */
#define CMDQ_SYNC_TOKEN_STREAM_EOF			641
/* Block Trigger thread until the ESD check finishes. */
#define CMDQ_SYNC_TOKEN_ESD_EOF				642
#define CMDQ_SYNC_TOKEN_STREAM_BLOCK			643
/* check CABC setup finish */
#define CMDQ_SYNC_TOKEN_CABC_EOF			644

/*VFP period token for Msync*/
#define CMDQ_SYNC_TOKEN_VFP_PERIOD			645
/* check vdo mode CABC setup finish */
#define CMDQ_SYNC_TOKEN_VDO_MODE_CABC_EOF   646

/* SW sync token for dual display */
#define CMDQ_SYNC_TOKEN_CONFIG_DIRTY_1			694
#define CMDQ_SYNC_TOKEN_STREAM_EOF_1			695
#define CMDQ_SYNC_TOKEN_ESD_EOF_1			696
#define CMDQ_SYNC_TOKEN_STREAM_BLOCK_1			697
#define CMDQ_SYNC_TOKEN_CABC_EOF_1			698

/* GPR access tokens (for HW register backup)
 * There are 15 32-bit GPR, 3 GPR form a set
 * (64-bit for address, 32-bit for value)
 * MUST NOT CHANGE, these tokens sync with MDP
 */
#define CMDQ_SYNC_TOKEN_GPR_SET_0			700
#define CMDQ_SYNC_TOKEN_GPR_SET_1			701
#define CMDQ_SYNC_TOKEN_GPR_SET_2			702
#define CMDQ_SYNC_TOKEN_GPR_SET_3			703
#define CMDQ_SYNC_TOKEN_GPR_SET_4			704

#define CMDQ_SYNC_TOKEN_TE_0				705
#define CMDQ_SYNC_TOKEN_PREFETCH_TE_0			706
#define CMDQ_SYNC_TOKEN_VIDLE_POWER_ON			707
#define CMDQ_SYNC_TOKEN_CHECK_TRIGGER_MERGE		708

/* Resource lock event to control resource in GCE thread */
#define CMDQ_SYNC_RESOURCE_WROT0			710
#define CMDQ_SYNC_RESOURCE_WROT1			711

/* HW TRACE sw token */
#define CMDQ_SYNC_TOKEN_HW_TRACE_WAIT			712
#define CMDQ_SYNC_TOKEN_HW_TRACE_LOCK			713

/* SW sync token for dual display */
#define CMDQ_SYNC_TOKEN_CONFIG_DIRTY_3			714
#define CMDQ_SYNC_TOKEN_STREAM_EOF_3			715
#define CMDQ_SYNC_TOKEN_ESD_EOF_3			716
#define CMDQ_SYNC_TOKEN_STREAM_BLOCK_3			717
#define CMDQ_SYNC_TOKEN_CABC_EOF_3			718
/* end of GCE-D sw token */

/* begin of GCE-M sw token */
/* IMGSYS_POOL */
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_1		514
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_2		515
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_3		516
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_4		517
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_5		518
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_6		519
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_7		520
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_8		521
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_9		522
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_10		523
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_11		524
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_12		525
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_13		526
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_14		527
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_15		528
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_16		529
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_17		530
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_18		531
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_19		532
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_20		533
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_21		534
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_22		535
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_23		536
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_24		537
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_25		538
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_26		539
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_27		540
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_28		541
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_29		542
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_30		543
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_31		544
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_32		545
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_33		546
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_34		547
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_35		548
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_36		549
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_37		550
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_38		551
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_39		552
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_40		553
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_41		554
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_42		555
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_43		556
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_44		557
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_45		558
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_46		559
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_47		560
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_48		561
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_49		562
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_50		563
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_51		564
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_52		565
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_53		566
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_54		567
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_55		568
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_56		569
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_57		570
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_58		571
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_59		572
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_60		573
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_61		574
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_62		575
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_63		576
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_64		577
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_65		578
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_66		579
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_67		580
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_68		581
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_69		582
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_70		583
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_71		584
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_72		585
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_73		586
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_74		587
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_75		588
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_76		589
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_77		590
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_78		591
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_79		592
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_80		593
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_81		594
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_82		595
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_83		596
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_84		597
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_85		598
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_86		599
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_87		600
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_88		601
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_89		602
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_90		603
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_91		604
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_92		605
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_93		606
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_94		607
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_95		608
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_96		609
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_97		610
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_98		611
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_99		612
#define	CMDQ_SYNC_TOKEN_IMGSYS_POOL_100		613

/* ISP sw token */
#define CMDQ_SYNC_TOKEN_MSS			665
#define CMDQ_SYNC_TOKEN_MSF			666
/* end of GCE-M sw token */

/* begin of common sw token */

/* Notify normal CMDQ there are some secure task done
 * MUST NOT CHANGE, this token sync with secure world
 */
#define CMDQ_SYNC_SECURE_THR_EOF			647

/* CMDQ use sw token */
#define CMDQ_SYNC_TOKEN_USER_0				649
#define CMDQ_SYNC_TOKEN_USER_1				650
#define CMDQ_SYNC_TOKEN_POLL_MONITOR			651
#define CMDQ_SYNC_TOKEN_TPR_LOCK			652

/* TZMP sw token */
#define CMDQ_SYNC_TOKEN_TZMP_DISP_WAIT			653
#define CMDQ_SYNC_TOKEN_TZMP_DISP_SET			654
#define CMDQ_SYNC_TOKEN_TZMP_ISP_WAIT			655
#define CMDQ_SYNC_TOKEN_TZMP_ISP_SET			656
#define CMDQ_SYNC_TOKEN_TZMP_AIE_WAIT			657
#define CMDQ_SYNC_TOKEN_TZMP_AIE_SET			658
#define CMDQ_SYNC_TOKEN_TZMP_ADL_WAIT			659
#define CMDQ_SYNC_TOKEN_TZMP_ADL_SET			660

/* PREBUILT sw token */
#define CMDQ_SYNC_TOKEN_PREBUILT_MDP_LOCK		682
#define CMDQ_SYNC_TOKEN_PREBUILT_MML_LOCK		685
#define CMDQ_SYNC_TOKEN_PREBUILT_VFMT_LOCK		688
#define CMDQ_SYNC_TOKEN_PREBUILT_DISP_LOCK		691
#define CMDQ_SYNC_TOKEN_DISP_VA_START			692
#define CMDQ_SYNC_TOKEN_DISP_VA_END			693

/* event for gpr timer, used in sleep and poll with timeout */
#define CMDQ_TOKEN_GPR_TIMER_R0				994
#define CMDQ_TOKEN_GPR_TIMER_R1				995
#define CMDQ_TOKEN_GPR_TIMER_R2				996
#define CMDQ_TOKEN_GPR_TIMER_R3				997
#define CMDQ_TOKEN_GPR_TIMER_R4				998
#define CMDQ_TOKEN_GPR_TIMER_R5				999
#define CMDQ_TOKEN_GPR_TIMER_R6				1000
#define CMDQ_TOKEN_GPR_TIMER_R7				1001
#define CMDQ_TOKEN_GPR_TIMER_R8				1002
#define CMDQ_TOKEN_GPR_TIMER_R9				1003
#define CMDQ_TOKEN_GPR_TIMER_R10			1004
#define CMDQ_TOKEN_GPR_TIMER_R11			1005
#define CMDQ_TOKEN_GPR_TIMER_R12			1006
#define CMDQ_TOKEN_GPR_TIMER_R13			1007
#define CMDQ_TOKEN_GPR_TIMER_R14			1008
#define CMDQ_TOKEN_GPR_TIMER_R15			1009

#define CMDQ_EVENT_MAX					0x3FF
/* end of common sw token */
/* CMDQ sw tokens END */

#endif
